// generated by stringer -type=lexerState; DO NOT EDIT

package main

import "fmt"

const _lexerState_name = "lexerStateNonelexerStateNameOrLabellexerStateNumber"

var _lexerState_index = [...]uint8{0, 14, 35, 51}

func (i lexerState) String() string {
	if i < 0 || i+1 >= lexerState(len(_lexerState_index)) {
		return fmt.Sprintf("lexerState(%d)", i)
	}
	return _lexerState_name[_lexerState_index[i]:_lexerState_index[i+1]]
}
