// generated by stringer -type=tokenType; DO NOT EDIT

package main

import "fmt"

const _tokenType_name = "tokenNametokenLabeltokenNumber"

var _tokenType_index = [...]uint8{0, 9, 19, 30}

func (i tokenType) String() string {
	i -= 1
	if i < 0 || i+1 >= tokenType(len(_tokenType_index)) {
		return fmt.Sprintf("tokenType(%d)", i+1)
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
